/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingAccountStartFlashloanInstructionAccounts = {
  marginfiAccount: PublicKey | Pda;
  signer: Signer;
  ixsSysvar: PublicKey | Pda;
};

// Data.
export type LendingAccountStartFlashloanInstructionData = {
  discriminator: Array<number>;
  endIndex: bigint;
};

export type LendingAccountStartFlashloanInstructionDataArgs = {
  endIndex: number | bigint;
};

export function getLendingAccountStartFlashloanInstructionDataSerializer(): Serializer<
  LendingAccountStartFlashloanInstructionDataArgs,
  LendingAccountStartFlashloanInstructionData
> {
  return mapSerializer<
    LendingAccountStartFlashloanInstructionDataArgs,
    any,
    LendingAccountStartFlashloanInstructionData
  >(
    struct<LendingAccountStartFlashloanInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['endIndex', u64()],
      ],
      { description: 'LendingAccountStartFlashloanInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [14, 131, 33, 220, 81, 186, 180, 107],
    })
  ) as Serializer<
    LendingAccountStartFlashloanInstructionDataArgs,
    LendingAccountStartFlashloanInstructionData
  >;
}

// Args.
export type LendingAccountStartFlashloanInstructionArgs =
  LendingAccountStartFlashloanInstructionDataArgs;

// Instruction.
export function lendingAccountStartFlashloan(
  context: Pick<Context, 'programs'>,
  input: LendingAccountStartFlashloanInstructionAccounts &
    LendingAccountStartFlashloanInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiAccount: {
      index: 0,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    signer: {
      index: 1,
      isWritable: false as boolean,
      value: input.signer ?? null,
    },
    ixsSysvar: {
      index: 2,
      isWritable: false as boolean,
      value: input.ixsSysvar ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: LendingAccountStartFlashloanInstructionArgs = {
    ...input,
  };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingAccountStartFlashloanInstructionDataSerializer().serialize(
      resolvedArgs as LendingAccountStartFlashloanInstructionDataArgs
    );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
