/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingPoolCollectBankFeesInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  bank: PublicKey | Pda;
  liquidityVaultAuthority: PublicKey | Pda;
  liquidityVault: PublicKey | Pda;
  insuranceVault: PublicKey | Pda;
  feeVault: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type LendingPoolCollectBankFeesInstructionData = {
  discriminator: Array<number>;
};

export type LendingPoolCollectBankFeesInstructionDataArgs = {};

export function getLendingPoolCollectBankFeesInstructionDataSerializer(): Serializer<
  LendingPoolCollectBankFeesInstructionDataArgs,
  LendingPoolCollectBankFeesInstructionData
> {
  return mapSerializer<
    LendingPoolCollectBankFeesInstructionDataArgs,
    any,
    LendingPoolCollectBankFeesInstructionData
  >(
    struct<LendingPoolCollectBankFeesInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LendingPoolCollectBankFeesInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [201, 5, 215, 116, 230, 92, 75, 150],
    })
  ) as Serializer<
    LendingPoolCollectBankFeesInstructionDataArgs,
    LendingPoolCollectBankFeesInstructionData
  >;
}

// Instruction.
export function lendingPoolCollectBankFees(
  context: Pick<Context, 'programs'>,
  input: LendingPoolCollectBankFeesInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    bank: { index: 1, isWritable: true as boolean, value: input.bank ?? null },
    liquidityVaultAuthority: {
      index: 2,
      isWritable: false as boolean,
      value: input.liquidityVaultAuthority ?? null,
    },
    liquidityVault: {
      index: 3,
      isWritable: true as boolean,
      value: input.liquidityVault ?? null,
    },
    insuranceVault: {
      index: 4,
      isWritable: true as boolean,
      value: input.insuranceVault ?? null,
    },
    feeVault: {
      index: 5,
      isWritable: true as boolean,
      value: input.feeVault ?? null,
    },
    tokenProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingPoolCollectBankFeesInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
