/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingAccountDepositInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  marginfiAccount: PublicKey | Pda;
  signer: Signer;
  bank: PublicKey | Pda;
  signerTokenAccount: PublicKey | Pda;
  bankLiquidityVault: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type LendingAccountDepositInstructionData = {
  discriminator: Array<number>;
  amount: bigint;
};

export type LendingAccountDepositInstructionDataArgs = {
  amount: number | bigint;
};

export function getLendingAccountDepositInstructionDataSerializer(): Serializer<
  LendingAccountDepositInstructionDataArgs,
  LendingAccountDepositInstructionData
> {
  return mapSerializer<
    LendingAccountDepositInstructionDataArgs,
    any,
    LendingAccountDepositInstructionData
  >(
    struct<LendingAccountDepositInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['amount', u64()],
      ],
      { description: 'LendingAccountDepositInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [171, 94, 235, 103, 82, 64, 212, 140],
    })
  ) as Serializer<
    LendingAccountDepositInstructionDataArgs,
    LendingAccountDepositInstructionData
  >;
}

// Args.
export type LendingAccountDepositInstructionArgs =
  LendingAccountDepositInstructionDataArgs;

// Instruction.
export function lendingAccountDeposit(
  context: Pick<Context, 'programs'>,
  input: LendingAccountDepositInstructionAccounts &
    LendingAccountDepositInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    marginfiAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    signer: {
      index: 2,
      isWritable: false as boolean,
      value: input.signer ?? null,
    },
    bank: { index: 3, isWritable: true as boolean, value: input.bank ?? null },
    signerTokenAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.signerTokenAccount ?? null,
    },
    bankLiquidityVault: {
      index: 5,
      isWritable: true as boolean,
      value: input.bankLiquidityVault ?? null,
    },
    tokenProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: LendingAccountDepositInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getLendingAccountDepositInstructionDataSerializer().serialize(
    resolvedArgs as LendingAccountDepositInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
