/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingAccountEndFlashloanInstructionAccounts = {
  marginfiAccount: PublicKey | Pda;
  signer: Signer;
};

// Data.
export type LendingAccountEndFlashloanInstructionData = {
  discriminator: Array<number>;
};

export type LendingAccountEndFlashloanInstructionDataArgs = {};

export function getLendingAccountEndFlashloanInstructionDataSerializer(): Serializer<
  LendingAccountEndFlashloanInstructionDataArgs,
  LendingAccountEndFlashloanInstructionData
> {
  return mapSerializer<
    LendingAccountEndFlashloanInstructionDataArgs,
    any,
    LendingAccountEndFlashloanInstructionData
  >(
    struct<LendingAccountEndFlashloanInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LendingAccountEndFlashloanInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [105, 124, 201, 106, 153, 2, 8, 156],
    })
  ) as Serializer<
    LendingAccountEndFlashloanInstructionDataArgs,
    LendingAccountEndFlashloanInstructionData
  >;
}

// Instruction.
export function lendingAccountEndFlashloan(
  context: Pick<Context, 'programs'>,
  input: LendingAccountEndFlashloanInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiAccount: {
      index: 0,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    signer: {
      index: 1,
      isWritable: false as boolean,
      value: input.signer ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingAccountEndFlashloanInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
