/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type MarginfiAccountInitializeInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  marginfiAccount: Signer;
  authority?: Signer;
  feePayer?: Signer;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type MarginfiAccountInitializeInstructionData = {
  discriminator: Array<number>;
};

export type MarginfiAccountInitializeInstructionDataArgs = {};

export function getMarginfiAccountInitializeInstructionDataSerializer(): Serializer<
  MarginfiAccountInitializeInstructionDataArgs,
  MarginfiAccountInitializeInstructionData
> {
  return mapSerializer<
    MarginfiAccountInitializeInstructionDataArgs,
    any,
    MarginfiAccountInitializeInstructionData
  >(
    struct<MarginfiAccountInitializeInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'MarginfiAccountInitializeInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [43, 78, 61, 255, 148, 52, 249, 154],
    })
  ) as Serializer<
    MarginfiAccountInitializeInstructionDataArgs,
    MarginfiAccountInitializeInstructionData
  >;
}

// Instruction.
export function marginfiAccountInitialize(
  context: Pick<Context, 'identity' | 'payer' | 'programs'>,
  input: MarginfiAccountInitializeInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    marginfiAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    authority: {
      index: 2,
      isWritable: false as boolean,
      value: input.authority ?? null,
    },
    feePayer: {
      index: 3,
      isWritable: true as boolean,
      value: input.feePayer ?? null,
    },
    systemProgram: {
      index: 4,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity;
  }
  if (!resolvedAccounts.feePayer.value) {
    resolvedAccounts.feePayer.value = context.payer;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getMarginfiAccountInitializeInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
