/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type MarginfiGroupInitializeInstructionAccounts = {
  marginfiGroup: Signer;
  admin: Signer;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type MarginfiGroupInitializeInstructionData = {
  discriminator: Array<number>;
};

export type MarginfiGroupInitializeInstructionDataArgs = {};

export function getMarginfiGroupInitializeInstructionDataSerializer(): Serializer<
  MarginfiGroupInitializeInstructionDataArgs,
  MarginfiGroupInitializeInstructionData
> {
  return mapSerializer<
    MarginfiGroupInitializeInstructionDataArgs,
    any,
    MarginfiGroupInitializeInstructionData
  >(
    struct<MarginfiGroupInitializeInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'MarginfiGroupInitializeInstructionData' }
    ),
    (value) => ({ ...value, discriminator: [255, 67, 67, 26, 94, 31, 34, 20] })
  ) as Serializer<
    MarginfiGroupInitializeInstructionDataArgs,
    MarginfiGroupInitializeInstructionData
  >;
}

// Instruction.
export function marginfiGroupInitialize(
  context: Pick<Context, 'programs'>,
  input: MarginfiGroupInitializeInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: true as boolean,
      value: input.marginfiGroup ?? null,
    },
    admin: {
      index: 1,
      isWritable: true as boolean,
      value: input.admin ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getMarginfiGroupInitializeInstructionDataSerializer().serialize(
    {}
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
