/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type UnsetAccountFlagInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  marginfiAccount: PublicKey | Pda;
  /** Admin only */
  admin: Signer;
};

// Data.
export type UnsetAccountFlagInstructionData = {
  discriminator: Array<number>;
  flag: bigint;
};

export type UnsetAccountFlagInstructionDataArgs = { flag: number | bigint };

export function getUnsetAccountFlagInstructionDataSerializer(): Serializer<
  UnsetAccountFlagInstructionDataArgs,
  UnsetAccountFlagInstructionData
> {
  return mapSerializer<
    UnsetAccountFlagInstructionDataArgs,
    any,
    UnsetAccountFlagInstructionData
  >(
    struct<UnsetAccountFlagInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['flag', u64()],
      ],
      { description: 'UnsetAccountFlagInstructionData' }
    ),
    (value) => ({ ...value, discriminator: [56, 81, 56, 85, 92, 49, 255, 70] })
  ) as Serializer<
    UnsetAccountFlagInstructionDataArgs,
    UnsetAccountFlagInstructionData
  >;
}

// Args.
export type UnsetAccountFlagInstructionArgs =
  UnsetAccountFlagInstructionDataArgs;

// Instruction.
export function unsetAccountFlag(
  context: Pick<Context, 'programs'>,
  input: UnsetAccountFlagInstructionAccounts & UnsetAccountFlagInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    marginfiAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    admin: {
      index: 2,
      isWritable: false as boolean,
      value: input.admin ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: UnsetAccountFlagInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getUnsetAccountFlagInstructionDataSerializer().serialize(
    resolvedArgs as UnsetAccountFlagInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
