/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  publicKey,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CreateProgramOpenOrdersInstructionAccounts = {
  openOrders: PublicKey | Pda;
  payer?: Signer;
  programAuthority: PublicKey | Pda;
  dexProgram: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  rent?: PublicKey | Pda;
  market: PublicKey | Pda;
};

// Data.
export type CreateProgramOpenOrdersInstructionData = {
  discriminator: Array<number>;
  id: number;
};

export type CreateProgramOpenOrdersInstructionDataArgs = { id: number };

export function getCreateProgramOpenOrdersInstructionDataSerializer(): Serializer<
  CreateProgramOpenOrdersInstructionDataArgs,
  CreateProgramOpenOrdersInstructionData
> {
  return mapSerializer<
    CreateProgramOpenOrdersInstructionDataArgs,
    any,
    CreateProgramOpenOrdersInstructionData
  >(
    struct<CreateProgramOpenOrdersInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['id', u8()],
      ],
      { description: 'CreateProgramOpenOrdersInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [28, 226, 32, 148, 188, 136, 113, 171],
    })
  ) as Serializer<
    CreateProgramOpenOrdersInstructionDataArgs,
    CreateProgramOpenOrdersInstructionData
  >;
}

// Args.
export type CreateProgramOpenOrdersInstructionArgs =
  CreateProgramOpenOrdersInstructionDataArgs;

// Instruction.
export function createProgramOpenOrders(
  context: Pick<Context, 'payer' | 'programs'>,
  input: CreateProgramOpenOrdersInstructionAccounts &
    CreateProgramOpenOrdersInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    openOrders: {
      index: 0,
      isWritable: true as boolean,
      value: input.openOrders ?? null,
    },
    payer: {
      index: 1,
      isWritable: true as boolean,
      value: input.payer ?? null,
    },
    programAuthority: {
      index: 2,
      isWritable: false as boolean,
      value: input.programAuthority ?? null,
    },
    dexProgram: {
      index: 3,
      isWritable: false as boolean,
      value: input.dexProgram ?? null,
    },
    systemProgram: {
      index: 4,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    rent: { index: 5, isWritable: false as boolean, value: input.rent ?? null },
    market: {
      index: 6,
      isWritable: false as boolean,
      value: input.market ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: CreateProgramOpenOrdersInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.payer.value) {
    resolvedAccounts.payer.value = context.payer;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.rent.value) {
    resolvedAccounts.rent.value = publicKey(
      'SysvarRent111111111111111111111111111111111'
    );
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCreateProgramOpenOrdersInstructionDataSerializer().serialize(
    resolvedArgs as CreateProgramOpenOrdersInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
