/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CreateTokenLedgerInstructionAccounts = {
  tokenLedger: Signer;
  payer?: Signer;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type CreateTokenLedgerInstructionData = { discriminator: Array<number> };

export type CreateTokenLedgerInstructionDataArgs = {};

export function getCreateTokenLedgerInstructionDataSerializer(): Serializer<
  CreateTokenLedgerInstructionDataArgs,
  CreateTokenLedgerInstructionData
> {
  return mapSerializer<
    CreateTokenLedgerInstructionDataArgs,
    any,
    CreateTokenLedgerInstructionData
  >(
    struct<CreateTokenLedgerInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'CreateTokenLedgerInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [232, 242, 197, 253, 240, 143, 129, 52],
    })
  ) as Serializer<
    CreateTokenLedgerInstructionDataArgs,
    CreateTokenLedgerInstructionData
  >;
}

// Instruction.
export function createTokenLedger(
  context: Pick<Context, 'payer' | 'programs'>,
  input: CreateTokenLedgerInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    tokenLedger: {
      index: 0,
      isWritable: true as boolean,
      value: input.tokenLedger ?? null,
    },
    payer: {
      index: 1,
      isWritable: true as boolean,
      value: input.payer ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.payer.value) {
    resolvedAccounts.payer.value = context.payer;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'splSystem',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCreateTokenLedgerInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
