/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u16,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';
import {
  RoutePlanStep,
  RoutePlanStepArgs,
  getRoutePlanStepSerializer,
} from '../types';

// Accounts.
export type ExactOutRouteInstructionAccounts = {
  tokenProgram?: PublicKey | Pda;
  userTransferAuthority: Signer;
  userSourceTokenAccount: PublicKey | Pda;
  userDestinationTokenAccount: PublicKey | Pda;
  destinationTokenAccount?: PublicKey | Pda;
  sourceMint: PublicKey | Pda;
  destinationMint: PublicKey | Pda;
  platformFeeAccount?: PublicKey | Pda;
  token2022Program?: PublicKey | Pda;
  eventAuthority: PublicKey | Pda;
  program: PublicKey | Pda;
};

// Data.
export type ExactOutRouteInstructionData = {
  discriminator: Array<number>;
  routePlan: Array<RoutePlanStep>;
  outAmount: bigint;
  quotedInAmount: bigint;
  slippageBps: number;
  platformFeeBps: number;
};

export type ExactOutRouteInstructionDataArgs = {
  routePlan: Array<RoutePlanStepArgs>;
  outAmount: number | bigint;
  quotedInAmount: number | bigint;
  slippageBps: number;
  platformFeeBps: number;
};

export function getExactOutRouteInstructionDataSerializer(): Serializer<
  ExactOutRouteInstructionDataArgs,
  ExactOutRouteInstructionData
> {
  return mapSerializer<
    ExactOutRouteInstructionDataArgs,
    any,
    ExactOutRouteInstructionData
  >(
    struct<ExactOutRouteInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['routePlan', array(getRoutePlanStepSerializer())],
        ['outAmount', u64()],
        ['quotedInAmount', u64()],
        ['slippageBps', u16()],
        ['platformFeeBps', u8()],
      ],
      { description: 'ExactOutRouteInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [208, 51, 239, 151, 123, 43, 237, 92],
    })
  ) as Serializer<
    ExactOutRouteInstructionDataArgs,
    ExactOutRouteInstructionData
  >;
}

// Args.
export type ExactOutRouteInstructionArgs = ExactOutRouteInstructionDataArgs;

// Instruction.
export function exactOutRoute(
  context: Pick<Context, 'programs'>,
  input: ExactOutRouteInstructionAccounts & ExactOutRouteInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    tokenProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    userTransferAuthority: {
      index: 1,
      isWritable: false as boolean,
      value: input.userTransferAuthority ?? null,
    },
    userSourceTokenAccount: {
      index: 2,
      isWritable: true as boolean,
      value: input.userSourceTokenAccount ?? null,
    },
    userDestinationTokenAccount: {
      index: 3,
      isWritable: true as boolean,
      value: input.userDestinationTokenAccount ?? null,
    },
    destinationTokenAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.destinationTokenAccount ?? null,
    },
    sourceMint: {
      index: 5,
      isWritable: false as boolean,
      value: input.sourceMint ?? null,
    },
    destinationMint: {
      index: 6,
      isWritable: false as boolean,
      value: input.destinationMint ?? null,
    },
    platformFeeAccount: {
      index: 7,
      isWritable: true as boolean,
      value: input.platformFeeAccount ?? null,
    },
    token2022Program: {
      index: 8,
      isWritable: false as boolean,
      value: input.token2022Program ?? null,
    },
    eventAuthority: {
      index: 9,
      isWritable: false as boolean,
      value: input.eventAuthority ?? null,
    },
    program: {
      index: 10,
      isWritable: false as boolean,
      value: input.program ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: ExactOutRouteInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getExactOutRouteInstructionDataSerializer().serialize(
    resolvedArgs as ExactOutRouteInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
