/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LifinityV2SwapInstructionAccounts = {
  swapProgram: PublicKey | Pda;
  authority?: PublicKey | Pda;
  amm: PublicKey | Pda;
  userTransferAuthority: PublicKey | Pda;
  sourceInfo: PublicKey | Pda;
  destinationInfo: PublicKey | Pda;
  swapSource: PublicKey | Pda;
  swapDestination: PublicKey | Pda;
  poolMint: PublicKey | Pda;
  feeAccount: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  oracleMainAccount: PublicKey | Pda;
  oracleSubAccount: PublicKey | Pda;
  oraclePcAccount: PublicKey | Pda;
};

// Data.
export type LifinityV2SwapInstructionData = { discriminator: Array<number> };

export type LifinityV2SwapInstructionDataArgs = {};

export function getLifinityV2SwapInstructionDataSerializer(): Serializer<
  LifinityV2SwapInstructionDataArgs,
  LifinityV2SwapInstructionData
> {
  return mapSerializer<
    LifinityV2SwapInstructionDataArgs,
    any,
    LifinityV2SwapInstructionData
  >(
    struct<LifinityV2SwapInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LifinityV2SwapInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [19, 152, 195, 245, 187, 144, 74, 227],
    })
  ) as Serializer<
    LifinityV2SwapInstructionDataArgs,
    LifinityV2SwapInstructionData
  >;
}

// Instruction.
export function lifinityV2Swap(
  context: Pick<Context, 'identity' | 'programs'>,
  input: LifinityV2SwapInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    swapProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.swapProgram ?? null,
    },
    authority: {
      index: 1,
      isWritable: false as boolean,
      value: input.authority ?? null,
    },
    amm: { index: 2, isWritable: true as boolean, value: input.amm ?? null },
    userTransferAuthority: {
      index: 3,
      isWritable: false as boolean,
      value: input.userTransferAuthority ?? null,
    },
    sourceInfo: {
      index: 4,
      isWritable: true as boolean,
      value: input.sourceInfo ?? null,
    },
    destinationInfo: {
      index: 5,
      isWritable: true as boolean,
      value: input.destinationInfo ?? null,
    },
    swapSource: {
      index: 6,
      isWritable: true as boolean,
      value: input.swapSource ?? null,
    },
    swapDestination: {
      index: 7,
      isWritable: true as boolean,
      value: input.swapDestination ?? null,
    },
    poolMint: {
      index: 8,
      isWritable: true as boolean,
      value: input.poolMint ?? null,
    },
    feeAccount: {
      index: 9,
      isWritable: true as boolean,
      value: input.feeAccount ?? null,
    },
    tokenProgram: {
      index: 10,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    oracleMainAccount: {
      index: 11,
      isWritable: false as boolean,
      value: input.oracleMainAccount ?? null,
    },
    oracleSubAccount: {
      index: 12,
      isWritable: false as boolean,
      value: input.oracleSubAccount ?? null,
    },
    oraclePcAccount: {
      index: 13,
      isWritable: false as boolean,
      value: input.oraclePcAccount ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.authority.value) {
    resolvedAccounts.authority.value = context.identity.publicKey;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getLifinityV2SwapInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
