/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type PerpsV2SwapInstructionAccounts = {
  swapProgram: PublicKey | Pda;
  owner: PublicKey | Pda;
  fundingAccount: PublicKey | Pda;
  receivingAccount: PublicKey | Pda;
  transferAuthority: PublicKey | Pda;
  perpetuals: PublicKey | Pda;
  pool: PublicKey | Pda;
  receivingCustody: PublicKey | Pda;
  receivingCustodyDovesPriceAccount: PublicKey | Pda;
  receivingCustodyPythnetPriceAccount: PublicKey | Pda;
  receivingCustodyTokenAccount: PublicKey | Pda;
  dispensingCustody: PublicKey | Pda;
  dispensingCustodyDovesPriceAccount: PublicKey | Pda;
  dispensingCustodyPythnetPriceAccount: PublicKey | Pda;
  dispensingCustodyTokenAccount: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  eventAuthority: PublicKey | Pda;
  program: PublicKey | Pda;
};

// Data.
export type PerpsV2SwapInstructionData = { discriminator: Array<number> };

export type PerpsV2SwapInstructionDataArgs = {};

export function getPerpsV2SwapInstructionDataSerializer(): Serializer<
  PerpsV2SwapInstructionDataArgs,
  PerpsV2SwapInstructionData
> {
  return mapSerializer<
    PerpsV2SwapInstructionDataArgs,
    any,
    PerpsV2SwapInstructionData
  >(
    struct<PerpsV2SwapInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'PerpsV2SwapInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [127, 245, 19, 158, 82, 250, 33, 18],
    })
  ) as Serializer<PerpsV2SwapInstructionDataArgs, PerpsV2SwapInstructionData>;
}

// Instruction.
export function perpsV2Swap(
  context: Pick<Context, 'programs'>,
  input: PerpsV2SwapInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    swapProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.swapProgram ?? null,
    },
    owner: {
      index: 1,
      isWritable: false as boolean,
      value: input.owner ?? null,
    },
    fundingAccount: {
      index: 2,
      isWritable: true as boolean,
      value: input.fundingAccount ?? null,
    },
    receivingAccount: {
      index: 3,
      isWritable: true as boolean,
      value: input.receivingAccount ?? null,
    },
    transferAuthority: {
      index: 4,
      isWritable: false as boolean,
      value: input.transferAuthority ?? null,
    },
    perpetuals: {
      index: 5,
      isWritable: false as boolean,
      value: input.perpetuals ?? null,
    },
    pool: { index: 6, isWritable: true as boolean, value: input.pool ?? null },
    receivingCustody: {
      index: 7,
      isWritable: true as boolean,
      value: input.receivingCustody ?? null,
    },
    receivingCustodyDovesPriceAccount: {
      index: 8,
      isWritable: false as boolean,
      value: input.receivingCustodyDovesPriceAccount ?? null,
    },
    receivingCustodyPythnetPriceAccount: {
      index: 9,
      isWritable: false as boolean,
      value: input.receivingCustodyPythnetPriceAccount ?? null,
    },
    receivingCustodyTokenAccount: {
      index: 10,
      isWritable: true as boolean,
      value: input.receivingCustodyTokenAccount ?? null,
    },
    dispensingCustody: {
      index: 11,
      isWritable: true as boolean,
      value: input.dispensingCustody ?? null,
    },
    dispensingCustodyDovesPriceAccount: {
      index: 12,
      isWritable: false as boolean,
      value: input.dispensingCustodyDovesPriceAccount ?? null,
    },
    dispensingCustodyPythnetPriceAccount: {
      index: 13,
      isWritable: false as boolean,
      value: input.dispensingCustodyPythnetPriceAccount ?? null,
    },
    dispensingCustodyTokenAccount: {
      index: 14,
      isWritable: true as boolean,
      value: input.dispensingCustodyTokenAccount ?? null,
    },
    tokenProgram: {
      index: 15,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    eventAuthority: {
      index: 16,
      isWritable: false as boolean,
      value: input.eventAuthority ?? null,
    },
    program: {
      index: 17,
      isWritable: false as boolean,
      value: input.program ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getPerpsV2SwapInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
