/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type PhoenixSwapInstructionAccounts = {
  swapProgram: PublicKey | Pda;
  logAuthority: PublicKey | Pda;
  market: PublicKey | Pda;
  trader: PublicKey | Pda;
  baseAccount: PublicKey | Pda;
  quoteAccount: PublicKey | Pda;
  baseVault: PublicKey | Pda;
  quoteVault: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type PhoenixSwapInstructionData = { discriminator: Array<number> };

export type PhoenixSwapInstructionDataArgs = {};

export function getPhoenixSwapInstructionDataSerializer(): Serializer<
  PhoenixSwapInstructionDataArgs,
  PhoenixSwapInstructionData
> {
  return mapSerializer<
    PhoenixSwapInstructionDataArgs,
    any,
    PhoenixSwapInstructionData
  >(
    struct<PhoenixSwapInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'PhoenixSwapInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [99, 66, 223, 95, 236, 131, 26, 140],
    })
  ) as Serializer<PhoenixSwapInstructionDataArgs, PhoenixSwapInstructionData>;
}

// Instruction.
export function phoenixSwap(
  context: Pick<Context, 'programs'>,
  input: PhoenixSwapInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    swapProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.swapProgram ?? null,
    },
    logAuthority: {
      index: 1,
      isWritable: false as boolean,
      value: input.logAuthority ?? null,
    },
    market: {
      index: 2,
      isWritable: true as boolean,
      value: input.market ?? null,
    },
    trader: {
      index: 3,
      isWritable: false as boolean,
      value: input.trader ?? null,
    },
    baseAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.baseAccount ?? null,
    },
    quoteAccount: {
      index: 5,
      isWritable: true as boolean,
      value: input.quoteAccount ?? null,
    },
    baseVault: {
      index: 6,
      isWritable: true as boolean,
      value: input.baseVault ?? null,
    },
    quoteVault: {
      index: 7,
      isWritable: true as boolean,
      value: input.quoteVault ?? null,
    },
    tokenProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getPhoenixSwapInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
