/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type RaydiumClmmSwapInstructionAccounts = {
  swapProgram: PublicKey | Pda;
  payer?: PublicKey | Pda;
  ammConfig: PublicKey | Pda;
  poolState: PublicKey | Pda;
  inputTokenAccount: PublicKey | Pda;
  outputTokenAccount: PublicKey | Pda;
  inputVault: PublicKey | Pda;
  outputVault: PublicKey | Pda;
  observationState: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  tickArray: PublicKey | Pda;
};

// Data.
export type RaydiumClmmSwapInstructionData = { discriminator: Array<number> };

export type RaydiumClmmSwapInstructionDataArgs = {};

export function getRaydiumClmmSwapInstructionDataSerializer(): Serializer<
  RaydiumClmmSwapInstructionDataArgs,
  RaydiumClmmSwapInstructionData
> {
  return mapSerializer<
    RaydiumClmmSwapInstructionDataArgs,
    any,
    RaydiumClmmSwapInstructionData
  >(
    struct<RaydiumClmmSwapInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'RaydiumClmmSwapInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [47, 184, 213, 193, 35, 210, 87, 4],
    })
  ) as Serializer<
    RaydiumClmmSwapInstructionDataArgs,
    RaydiumClmmSwapInstructionData
  >;
}

// Instruction.
export function raydiumClmmSwap(
  context: Pick<Context, 'payer' | 'programs'>,
  input: RaydiumClmmSwapInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    swapProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.swapProgram ?? null,
    },
    payer: {
      index: 1,
      isWritable: false as boolean,
      value: input.payer ?? null,
    },
    ammConfig: {
      index: 2,
      isWritable: false as boolean,
      value: input.ammConfig ?? null,
    },
    poolState: {
      index: 3,
      isWritable: true as boolean,
      value: input.poolState ?? null,
    },
    inputTokenAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.inputTokenAccount ?? null,
    },
    outputTokenAccount: {
      index: 5,
      isWritable: true as boolean,
      value: input.outputTokenAccount ?? null,
    },
    inputVault: {
      index: 6,
      isWritable: true as boolean,
      value: input.inputVault ?? null,
    },
    outputVault: {
      index: 7,
      isWritable: true as boolean,
      value: input.outputVault ?? null,
    },
    observationState: {
      index: 8,
      isWritable: true as boolean,
      value: input.observationState ?? null,
    },
    tokenProgram: {
      index: 9,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    tickArray: {
      index: 10,
      isWritable: true as boolean,
      value: input.tickArray ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.payer.value) {
    resolvedAccounts.payer.value = context.payer.publicKey;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getRaydiumClmmSwapInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
