/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u16,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';
import {
  RoutePlanStep,
  RoutePlanStepArgs,
  getRoutePlanStepSerializer,
} from '../types';

// Accounts.
export type RouteWithTokenLedgerInstructionAccounts = {
  tokenProgram?: PublicKey | Pda;
  userTransferAuthority: Signer;
  userSourceTokenAccount: PublicKey | Pda;
  userDestinationTokenAccount: PublicKey | Pda;
  destinationTokenAccount?: PublicKey | Pda;
  destinationMint: PublicKey | Pda;
  platformFeeAccount?: PublicKey | Pda;
  tokenLedger: PublicKey | Pda;
  eventAuthority: PublicKey | Pda;
  program: PublicKey | Pda;
};

// Data.
export type RouteWithTokenLedgerInstructionData = {
  discriminator: Array<number>;
  routePlan: Array<RoutePlanStep>;
  quotedOutAmount: bigint;
  slippageBps: number;
  platformFeeBps: number;
};

export type RouteWithTokenLedgerInstructionDataArgs = {
  routePlan: Array<RoutePlanStepArgs>;
  quotedOutAmount: number | bigint;
  slippageBps: number;
  platformFeeBps: number;
};

export function getRouteWithTokenLedgerInstructionDataSerializer(): Serializer<
  RouteWithTokenLedgerInstructionDataArgs,
  RouteWithTokenLedgerInstructionData
> {
  return mapSerializer<
    RouteWithTokenLedgerInstructionDataArgs,
    any,
    RouteWithTokenLedgerInstructionData
  >(
    struct<RouteWithTokenLedgerInstructionData>(
      [
        ['discriminator', array(u8(), { size: 8 })],
        ['routePlan', array(getRoutePlanStepSerializer())],
        ['quotedOutAmount', u64()],
        ['slippageBps', u16()],
        ['platformFeeBps', u8()],
      ],
      { description: 'RouteWithTokenLedgerInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [150, 86, 71, 116, 167, 93, 14, 104],
    })
  ) as Serializer<
    RouteWithTokenLedgerInstructionDataArgs,
    RouteWithTokenLedgerInstructionData
  >;
}

// Args.
export type RouteWithTokenLedgerInstructionArgs =
  RouteWithTokenLedgerInstructionDataArgs;

// Instruction.
export function routeWithTokenLedger(
  context: Pick<Context, 'programs'>,
  input: RouteWithTokenLedgerInstructionAccounts &
    RouteWithTokenLedgerInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    tokenProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    userTransferAuthority: {
      index: 1,
      isWritable: false as boolean,
      value: input.userTransferAuthority ?? null,
    },
    userSourceTokenAccount: {
      index: 2,
      isWritable: true as boolean,
      value: input.userSourceTokenAccount ?? null,
    },
    userDestinationTokenAccount: {
      index: 3,
      isWritable: true as boolean,
      value: input.userDestinationTokenAccount ?? null,
    },
    destinationTokenAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.destinationTokenAccount ?? null,
    },
    destinationMint: {
      index: 5,
      isWritable: false as boolean,
      value: input.destinationMint ?? null,
    },
    platformFeeAccount: {
      index: 6,
      isWritable: true as boolean,
      value: input.platformFeeAccount ?? null,
    },
    tokenLedger: {
      index: 7,
      isWritable: false as boolean,
      value: input.tokenLedger ?? null,
    },
    eventAuthority: {
      index: 8,
      isWritable: false as boolean,
      value: input.eventAuthority ?? null,
    },
    program: {
      index: 9,
      isWritable: false as boolean,
      value: input.program ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: RouteWithTokenLedgerInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getRouteWithTokenLedgerInstructionDataSerializer().serialize(
    resolvedArgs as RouteWithTokenLedgerInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
