/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type SaberAddDecimalsInstructionAccounts = {
  addDecimalsProgram: PublicKey | Pda;
  wrapper: PublicKey | Pda;
  wrapperMint: PublicKey | Pda;
  wrapperUnderlyingTokens: PublicKey | Pda;
  owner: PublicKey | Pda;
  userUnderlyingTokens: PublicKey | Pda;
  userWrappedTokens: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type SaberAddDecimalsInstructionData = { discriminator: Array<number> };

export type SaberAddDecimalsInstructionDataArgs = {};

export function getSaberAddDecimalsInstructionDataSerializer(): Serializer<
  SaberAddDecimalsInstructionDataArgs,
  SaberAddDecimalsInstructionData
> {
  return mapSerializer<
    SaberAddDecimalsInstructionDataArgs,
    any,
    SaberAddDecimalsInstructionData
  >(
    struct<SaberAddDecimalsInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'SaberAddDecimalsInstructionData' }
    ),
    (value) => ({ ...value, discriminator: [36, 53, 231, 184, 7, 181, 5, 238] })
  ) as Serializer<
    SaberAddDecimalsInstructionDataArgs,
    SaberAddDecimalsInstructionData
  >;
}

// Instruction.
export function saberAddDecimals(
  context: Pick<Context, 'programs'>,
  input: SaberAddDecimalsInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    addDecimalsProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.addDecimalsProgram ?? null,
    },
    wrapper: {
      index: 1,
      isWritable: false as boolean,
      value: input.wrapper ?? null,
    },
    wrapperMint: {
      index: 2,
      isWritable: true as boolean,
      value: input.wrapperMint ?? null,
    },
    wrapperUnderlyingTokens: {
      index: 3,
      isWritable: true as boolean,
      value: input.wrapperUnderlyingTokens ?? null,
    },
    owner: {
      index: 4,
      isWritable: false as boolean,
      value: input.owner ?? null,
    },
    userUnderlyingTokens: {
      index: 5,
      isWritable: true as boolean,
      value: input.userUnderlyingTokens ?? null,
    },
    userWrappedTokens: {
      index: 6,
      isWritable: true as boolean,
      value: input.userWrappedTokens ?? null,
    },
    tokenProgram: {
      index: 7,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getSaberAddDecimalsInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
