/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type SymmetrySwapInstructionAccounts = {
  swapProgram: PublicKey | Pda;
  buyer: PublicKey | Pda;
  fundState: PublicKey | Pda;
  pdaAccount: PublicKey | Pda;
  pdaFromTokenAccount: PublicKey | Pda;
  buyerFromTokenAccount: PublicKey | Pda;
  pdaToTokenAccount: PublicKey | Pda;
  buyerToTokenAccount: PublicKey | Pda;
  swapFeeAccount: PublicKey | Pda;
  hostFeeAccount: PublicKey | Pda;
  managerFeeAccount: PublicKey | Pda;
  tokenList: PublicKey | Pda;
  prismData: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type SymmetrySwapInstructionData = { discriminator: Array<number> };

export type SymmetrySwapInstructionDataArgs = {};

export function getSymmetrySwapInstructionDataSerializer(): Serializer<
  SymmetrySwapInstructionDataArgs,
  SymmetrySwapInstructionData
> {
  return mapSerializer<
    SymmetrySwapInstructionDataArgs,
    any,
    SymmetrySwapInstructionData
  >(
    struct<SymmetrySwapInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'SymmetrySwapInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [17, 114, 237, 234, 154, 12, 185, 116],
    })
  ) as Serializer<SymmetrySwapInstructionDataArgs, SymmetrySwapInstructionData>;
}

// Instruction.
export function symmetrySwap(
  context: Pick<Context, 'programs'>,
  input: SymmetrySwapInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'jupiter',
    'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
  );

  // Accounts.
  const resolvedAccounts = {
    swapProgram: {
      index: 0,
      isWritable: false as boolean,
      value: input.swapProgram ?? null,
    },
    buyer: {
      index: 1,
      isWritable: false as boolean,
      value: input.buyer ?? null,
    },
    fundState: {
      index: 2,
      isWritable: true as boolean,
      value: input.fundState ?? null,
    },
    pdaAccount: {
      index: 3,
      isWritable: false as boolean,
      value: input.pdaAccount ?? null,
    },
    pdaFromTokenAccount: {
      index: 4,
      isWritable: true as boolean,
      value: input.pdaFromTokenAccount ?? null,
    },
    buyerFromTokenAccount: {
      index: 5,
      isWritable: true as boolean,
      value: input.buyerFromTokenAccount ?? null,
    },
    pdaToTokenAccount: {
      index: 6,
      isWritable: true as boolean,
      value: input.pdaToTokenAccount ?? null,
    },
    buyerToTokenAccount: {
      index: 7,
      isWritable: true as boolean,
      value: input.buyerToTokenAccount ?? null,
    },
    swapFeeAccount: {
      index: 8,
      isWritable: true as boolean,
      value: input.swapFeeAccount ?? null,
    },
    hostFeeAccount: {
      index: 9,
      isWritable: true as boolean,
      value: input.hostFeeAccount ?? null,
    },
    managerFeeAccount: {
      index: 10,
      isWritable: true as boolean,
      value: input.managerFeeAccount ?? null,
    },
    tokenList: {
      index: 11,
      isWritable: false as boolean,
      value: input.tokenList ?? null,
    },
    prismData: {
      index: 12,
      isWritable: false as boolean,
      value: input.prismData ?? null,
    },
    tokenProgram: {
      index: 13,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getSymmetrySwapInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
