/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Serializer,
  struct,
  u16,
  u64,
} from '@metaplex-foundation/umi/serializers';

export type AmountWithSlippage = { amount: bigint; slippageBps: number };

export type AmountWithSlippageArgs = {
  amount: number | bigint;
  slippageBps: number;
};

export function getAmountWithSlippageSerializer(): Serializer<
  AmountWithSlippageArgs,
  AmountWithSlippage
> {
  return struct<AmountWithSlippage>(
    [
      ['amount', u64()],
      ['slippageBps', u16()],
    ],
    { description: 'AmountWithSlippage' }
  ) as Serializer<AmountWithSlippageArgs, AmountWithSlippage>;
}
