/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Serializer,
  array,
  struct,
} from '@metaplex-foundation/umi/serializers';
import {
  RemainingAccountsSlice,
  RemainingAccountsSliceArgs,
  getRemainingAccountsSliceSerializer,
} from '.';

export type RemainingAccountsInfo = { slices: Array<RemainingAccountsSlice> };

export type RemainingAccountsInfoArgs = {
  slices: Array<RemainingAccountsSliceArgs>;
};

export function getRemainingAccountsInfoSerializer(): Serializer<
  RemainingAccountsInfoArgs,
  RemainingAccountsInfo
> {
  return struct<RemainingAccountsInfo>(
    [['slices', array(getRemainingAccountsSliceSerializer())]],
    { description: 'RemainingAccountsInfo' }
  ) as Serializer<RemainingAccountsInfoArgs, RemainingAccountsInfo>;
}
