/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, struct, u8 } from '@metaplex-foundation/umi/serializers';
import { AccountsType, AccountsTypeArgs, getAccountsTypeSerializer } from '.';

export type RemainingAccountsSlice = {
  accountsType: AccountsType;
  length: number;
};

export type RemainingAccountsSliceArgs = {
  accountsType: AccountsTypeArgs;
  length: number;
};

export function getRemainingAccountsSliceSerializer(): Serializer<
  RemainingAccountsSliceArgs,
  RemainingAccountsSlice
> {
  return struct<RemainingAccountsSlice>(
    [
      ['accountsType', getAccountsTypeSerializer()],
      ['length', u8()],
    ],
    { description: 'RemainingAccountsSlice' }
  ) as Serializer<RemainingAccountsSliceArgs, RemainingAccountsSlice>;
}
