/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, scalarEnum } from '@metaplex-foundation/umi/serializers';

export enum Side {
  Bid,
  Ask,
}

export type SideArgs = Side;

export function getSideSerializer(): Serializer<SideArgs, Side> {
  return scalarEnum<Side>(Side, { description: 'Side' }) as Serializer<
    SideArgs,
    Side
  >;
}
