/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  publicKey as publicKeySerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import { PriceMessage, PriceMessageArgs, getPriceMessageSerializer } from '.';

export type PriceUpdateV2 = {
  writeAuthority: PublicKey;
  verificationLevel: number;
  priceMessage: PriceMessage;
  postedSlot: bigint;
};

export type PriceUpdateV2Args = {
  writeAuthority: PublicKey;
  verificationLevel: number;
  priceMessage: PriceMessageArgs;
  postedSlot: number | bigint;
};

export function getPriceUpdateV2Serializer(): Serializer<
  PriceUpdateV2Args,
  PriceUpdateV2
> {
  return struct<PriceUpdateV2>(
    [
      ['writeAuthority', publicKeySerializer()],
      ['verificationLevel', u8()],
      ['priceMessage', getPriceMessageSerializer()],
      ['postedSlot', u64()],
    ],
    { description: 'PriceUpdateV2' }
  ) as Serializer<PriceUpdateV2Args, PriceUpdateV2>;
}
