/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, scalarEnum } from '@metaplex-foundation/umi/serializers';

export enum BankVaultType {
  Liquidity,
  Insurance,
  Fee,
}

export type BankVaultTypeArgs = BankVaultType;

export function getBankVaultTypeSerializer(): Serializer<
  BankVaultTypeArgs,
  BankVaultType
> {
  return scalarEnum<BankVaultType>(BankVaultType, {
    description: 'BankVaultType',
  }) as Serializer<BankVaultTypeArgs, BankVaultType>;
}
