/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Serializer,
  array,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import { Balance, BalanceArgs, getBalanceSerializer } from '.';

export type LendingAccount = {
  balances: Array<Balance>;
  padding: Array<bigint>;
};

export type LendingAccountArgs = {
  balances: Array<BalanceArgs>;
  padding: Array<number | bigint>;
};

export function getLendingAccountSerializer(): Serializer<
  LendingAccountArgs,
  LendingAccount
> {
  return struct<LendingAccount>(
    [
      ['balances', array(getBalanceSerializer(), { size: 16 })],
      ['padding', array(u64(), { size: 8 })],
    ],
    { description: 'LendingAccount' }
  ) as Serializer<LendingAccountArgs, LendingAccount>;
}
