/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';
import { OracleSetup, OracleSetupArgs, getOracleSetupSerializer } from '.';

export type OracleConfig = { setup: OracleSetup; keys: Array<PublicKey> };

export type OracleConfigArgs = {
  setup: OracleSetupArgs;
  keys: Array<PublicKey>;
};

export function getOracleConfigSerializer(): Serializer<
  OracleConfigArgs,
  OracleConfig
> {
  return struct<OracleConfig>(
    [
      ['setup', getOracleSetupSerializer()],
      ['keys', array(publicKeySerializer(), { size: 5 })],
    ],
    { description: 'OracleConfig' }
  ) as Serializer<OracleConfigArgs, OracleConfig>;
}
