/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import { getMarginfiErrorFromCode, getMarginfiErrorFromName } from '../errors';

export const MARGINFI_PROGRAM_ID =
  'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA' as PublicKey<'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'>;

export function createMarginfiProgram(): Program {
  return {
    name: 'marginfi',
    publicKey: MARGINFI_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getMarginfiErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getMarginfiErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getMarginfiProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('marginfi', clusterFilter);
}

export function getMarginfiProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'marginfi',
    MARGINFI_PROGRAM_ID,
    clusterFilter
  );
}
