/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingAccountCloseBalanceInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  marginfiAccount: PublicKey | Pda;
  signer: Signer;
  bank: PublicKey | Pda;
};

// Data.
export type LendingAccountCloseBalanceInstructionData = {
  discriminator: Array<number>;
};

export type LendingAccountCloseBalanceInstructionDataArgs = {};

export function getLendingAccountCloseBalanceInstructionDataSerializer(): Serializer<
  LendingAccountCloseBalanceInstructionDataArgs,
  LendingAccountCloseBalanceInstructionData
> {
  return mapSerializer<
    LendingAccountCloseBalanceInstructionDataArgs,
    any,
    LendingAccountCloseBalanceInstructionData
  >(
    struct<LendingAccountCloseBalanceInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LendingAccountCloseBalanceInstructionData' }
    ),
    (value) => ({ ...value, discriminator: [245, 54, 41, 4, 243, 202, 31, 17] })
  ) as Serializer<
    LendingAccountCloseBalanceInstructionDataArgs,
    LendingAccountCloseBalanceInstructionData
  >;
}

// Instruction.
export function lendingAccountCloseBalance(
  context: Pick<Context, 'programs'>,
  input: LendingAccountCloseBalanceInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    marginfiAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    signer: {
      index: 2,
      isWritable: false as boolean,
      value: input.signer ?? null,
    },
    bank: { index: 3, isWritable: true as boolean, value: input.bank ?? null },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingAccountCloseBalanceInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
