/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingPoolHandleBankruptcyInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  admin: Signer;
  bank: PublicKey | Pda;
  marginfiAccount: PublicKey | Pda;
  liquidityVault: PublicKey | Pda;
  insuranceVault: PublicKey | Pda;
  insuranceVaultAuthority: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type LendingPoolHandleBankruptcyInstructionData = {
  discriminator: Array<number>;
};

export type LendingPoolHandleBankruptcyInstructionDataArgs = {};

export function getLendingPoolHandleBankruptcyInstructionDataSerializer(): Serializer<
  LendingPoolHandleBankruptcyInstructionDataArgs,
  LendingPoolHandleBankruptcyInstructionData
> {
  return mapSerializer<
    LendingPoolHandleBankruptcyInstructionDataArgs,
    any,
    LendingPoolHandleBankruptcyInstructionData
  >(
    struct<LendingPoolHandleBankruptcyInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LendingPoolHandleBankruptcyInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [162, 11, 56, 139, 90, 128, 70, 173],
    })
  ) as Serializer<
    LendingPoolHandleBankruptcyInstructionDataArgs,
    LendingPoolHandleBankruptcyInstructionData
  >;
}

// Instruction.
export function lendingPoolHandleBankruptcy(
  context: Pick<Context, 'programs'>,
  input: LendingPoolHandleBankruptcyInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    admin: {
      index: 1,
      isWritable: false as boolean,
      value: input.admin ?? null,
    },
    bank: { index: 2, isWritable: true as boolean, value: input.bank ?? null },
    marginfiAccount: {
      index: 3,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    liquidityVault: {
      index: 4,
      isWritable: true as boolean,
      value: input.liquidityVault ?? null,
    },
    insuranceVault: {
      index: 5,
      isWritable: true as boolean,
      value: input.insuranceVault ?? null,
    },
    insuranceVaultAuthority: {
      index: 6,
      isWritable: false as boolean,
      value: input.insuranceVaultAuthority ?? null,
    },
    tokenProgram: {
      index: 7,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingPoolHandleBankruptcyInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
