/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type LendingAccountWithdrawEmissionsInstructionAccounts = {
  marginfiGroup: PublicKey | Pda;
  marginfiAccount: PublicKey | Pda;
  signer: Signer;
  bank: PublicKey | Pda;
  emissionsMint: PublicKey | Pda;
  emissionsAuth: PublicKey | Pda;
  emissionsVault: PublicKey | Pda;
  destinationAccount: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
};

// Data.
export type LendingAccountWithdrawEmissionsInstructionData = {
  discriminator: Array<number>;
};

export type LendingAccountWithdrawEmissionsInstructionDataArgs = {};

export function getLendingAccountWithdrawEmissionsInstructionDataSerializer(): Serializer<
  LendingAccountWithdrawEmissionsInstructionDataArgs,
  LendingAccountWithdrawEmissionsInstructionData
> {
  return mapSerializer<
    LendingAccountWithdrawEmissionsInstructionDataArgs,
    any,
    LendingAccountWithdrawEmissionsInstructionData
  >(
    struct<LendingAccountWithdrawEmissionsInstructionData>(
      [['discriminator', array(u8(), { size: 8 })]],
      { description: 'LendingAccountWithdrawEmissionsInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: [234, 22, 84, 214, 118, 176, 140, 170],
    })
  ) as Serializer<
    LendingAccountWithdrawEmissionsInstructionDataArgs,
    LendingAccountWithdrawEmissionsInstructionData
  >;
}

// Instruction.
export function lendingAccountWithdrawEmissions(
  context: Pick<Context, 'programs'>,
  input: LendingAccountWithdrawEmissionsInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'marginfi',
    'MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA'
  );

  // Accounts.
  const resolvedAccounts = {
    marginfiGroup: {
      index: 0,
      isWritable: false as boolean,
      value: input.marginfiGroup ?? null,
    },
    marginfiAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.marginfiAccount ?? null,
    },
    signer: {
      index: 2,
      isWritable: false as boolean,
      value: input.signer ?? null,
    },
    bank: { index: 3, isWritable: true as boolean, value: input.bank ?? null },
    emissionsMint: {
      index: 4,
      isWritable: false as boolean,
      value: input.emissionsMint ?? null,
    },
    emissionsAuth: {
      index: 5,
      isWritable: false as boolean,
      value: input.emissionsAuth ?? null,
    },
    emissionsVault: {
      index: 6,
      isWritable: true as boolean,
      value: input.emissionsVault ?? null,
    },
    destinationAccount: {
      index: 7,
      isWritable: true as boolean,
      value: input.destinationAccount ?? null,
    },
    tokenProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'splToken',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getLendingAccountWithdrawEmissionsInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
