/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Option, OptionOrNullable, PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  option,
  publicKey as publicKeySerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';

export type AccountEventHeader = {
  signer: Option<PublicKey>;
  marginfiAccount: PublicKey;
  marginfiAccountAuthority: PublicKey;
  marginfiGroup: PublicKey;
};

export type AccountEventHeaderArgs = {
  signer: OptionOrNullable<PublicKey>;
  marginfiAccount: PublicKey;
  marginfiAccountAuthority: PublicKey;
  marginfiGroup: PublicKey;
};

export function getAccountEventHeaderSerializer(): Serializer<
  AccountEventHeaderArgs,
  AccountEventHeader
> {
  return struct<AccountEventHeader>(
    [
      ['signer', option(publicKeySerializer())],
      ['marginfiAccount', publicKeySerializer()],
      ['marginfiAccountAuthority', publicKeySerializer()],
      ['marginfiGroup', publicKeySerializer()],
    ],
    { description: 'AccountEventHeader' }
  ) as Serializer<AccountEventHeaderArgs, AccountEventHeader>;
}
