/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, scalarEnum } from '@metaplex-foundation/umi/serializers';

export enum BalanceIncreaseType {
  Any,
  RepayOnly,
  DepositOnly,
  BypassDepositLimit,
}

export type BalanceIncreaseTypeArgs = BalanceIncreaseType;

export function getBalanceIncreaseTypeSerializer(): Serializer<
  BalanceIncreaseTypeArgs,
  BalanceIncreaseType
> {
  return scalarEnum<BalanceIncreaseType>(BalanceIncreaseType, {
    description: 'BalanceIncreaseType',
  }) as Serializer<BalanceIncreaseTypeArgs, BalanceIncreaseType>;
}
