/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  array,
  publicKey as publicKeySerializer,
  struct,
  u64,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  BankOperationalState,
  BankOperationalStateArgs,
  InterestRateConfig,
  InterestRateConfigArgs,
  OracleSetup,
  OracleSetupArgs,
  RiskTier,
  RiskTierArgs,
  WrappedI80F48,
  WrappedI80F48Args,
  getBankOperationalStateSerializer,
  getInterestRateConfigSerializer,
  getOracleSetupSerializer,
  getRiskTierSerializer,
  getWrappedI80F48Serializer,
} from '.';

/** TODO: Convert weights to (u64, u64) to avoid precision loss (maybe?) */
export type BankConfig = {
  assetWeightInit: WrappedI80F48;
  assetWeightMaint: WrappedI80F48;
  liabilityWeightInit: WrappedI80F48;
  liabilityWeightMaint: WrappedI80F48;
  depositLimit: bigint;
  interestRateConfig: InterestRateConfig;
  operationalState: BankOperationalState;
  oracleSetup: OracleSetup;
  oracleKeys: Array<PublicKey>;
  autoPadding0: Array<number>;
  borrowLimit: bigint;
  riskTier: RiskTier;
  autoPadding1: Array<number>;
  /**
   * USD denominated limit for calculating asset value for initialization margin requirements.
   * Example, if total SOL deposits are equal to $1M and the limit it set to $500K,
   * then SOL assets will be discounted by 50%.
   *
   * In other words the max value of liabilities that can be backed by the asset is $500K.
   * This is useful for limiting the damage of orcale attacks.
   *
   * Value is UI USD value, for example value 100 -> $100
   */
  totalAssetValueInitLimit: bigint;
  padding: Array<bigint>;
};

export type BankConfigArgs = {
  assetWeightInit: WrappedI80F48Args;
  assetWeightMaint: WrappedI80F48Args;
  liabilityWeightInit: WrappedI80F48Args;
  liabilityWeightMaint: WrappedI80F48Args;
  depositLimit: number | bigint;
  interestRateConfig: InterestRateConfigArgs;
  operationalState: BankOperationalStateArgs;
  oracleSetup: OracleSetupArgs;
  oracleKeys: Array<PublicKey>;
  autoPadding0: Array<number>;
  borrowLimit: number | bigint;
  riskTier: RiskTierArgs;
  autoPadding1: Array<number>;
  /**
   * USD denominated limit for calculating asset value for initialization margin requirements.
   * Example, if total SOL deposits are equal to $1M and the limit it set to $500K,
   * then SOL assets will be discounted by 50%.
   *
   * In other words the max value of liabilities that can be backed by the asset is $500K.
   * This is useful for limiting the damage of orcale attacks.
   *
   * Value is UI USD value, for example value 100 -> $100
   */
  totalAssetValueInitLimit: number | bigint;
  padding: Array<number | bigint>;
};

export function getBankConfigSerializer(): Serializer<
  BankConfigArgs,
  BankConfig
> {
  return struct<BankConfig>(
    [
      ['assetWeightInit', getWrappedI80F48Serializer()],
      ['assetWeightMaint', getWrappedI80F48Serializer()],
      ['liabilityWeightInit', getWrappedI80F48Serializer()],
      ['liabilityWeightMaint', getWrappedI80F48Serializer()],
      ['depositLimit', u64()],
      ['interestRateConfig', getInterestRateConfigSerializer()],
      ['operationalState', getBankOperationalStateSerializer()],
      ['oracleSetup', getOracleSetupSerializer()],
      ['oracleKeys', array(publicKeySerializer(), { size: 5 })],
      ['autoPadding0', array(u8(), { size: 6 })],
      ['borrowLimit', u64()],
      ['riskTier', getRiskTierSerializer()],
      ['autoPadding1', array(u8(), { size: 7 })],
      ['totalAssetValueInitLimit', u64()],
      ['padding', array(u64(), { size: 5 })],
    ],
    { description: 'BankConfig' }
  ) as Serializer<BankConfigArgs, BankConfig>;
}
